### ISSUE TITLE
IE11 Error: Accessing the 'caller' property of a function or arguments object is not allowed in strict mode

### ISSUE THREAD

**Issue by trotil** [codewareio/ngrx-store-freeze#7]
Deep freeze dependency gives errors on IE 11 when models of state contain functions. For example getters.

This issue is posted also on deep-freeze library:

https://github.com/substack/deep-freeze/issues/6

They suggest using deep-freeze-strict version, which seem to work better for us.

https://www.npmjs.com/package/deep-freeze-strict

**Comment by tsm91** [comment]
Hi @trotil 

Replaced `deep-freeze` with `deep-freeze-strict`: https://github.com/codewareio/ngrx-store-freeze/commit/26ab6117170e1bc75ba57fe7cff7f902f937e52b

`v0.1.5` is published on npm

P.S: I dont use ngrx / redux architecture at work because it slowed me down quite a bit. Which means i didn't test if this works. Please ping me if it doesn't.

**Comment by trotil** [comment]
Thanks tsm91, ngrx indeed takes time, but we decided to make this investment as it gives a nice answer to many of our everyday state management problems :) And we know the project will be quite big.
